"""initial migration

Revision ID: 66656ef67e3f
Revises: 
Create Date: 2026-01-06 19:52:20.344123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66656ef67e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
